### ISSUE TITLE
Création d'un plugin à partir de customapp

### ISSUE THREAD

**Issue by qforgeot** [PluginsOCSInventory-NG/customapp#2]
Bonjour, 
J'ai tenté de créer mon propre plugin en prenant comme base ce plugin.
J'ai respecté tous les fichiers, les syntaxes etc... mais je n'arrive pas à l'installer. Il me dit que le plugin est non valide.
Pouvez-vous me dire s'il existe une doc ou des bonnes pratiques pour développer son plugin ?
Sinon, serait-il possible d'avoir de l'aide ?
Pour info, j'arrive sans problème à installer d'autres plugins dont customapp.
Merci d'avance

**Comment by steph78630** [comment]
Bonjour @qforgeot,

malheureusement, pas de doc ou en tout cas pas à jour.

Si j'ai accès à ton plugin, je peux jeter un coup d'œil pour le débuguer...

Cordialement, Stéphane

**Comment by steph78630** [comment]
Je pense que c'est réglé depuis... ;-)
